[build]
publish = "public"
command = "echo 'No build step required.'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "netlify/functions/secrets/**",
    "netlify/functions/helpers/**"
  ]
  
  [functions."*"]
    external_node_modules = ["googleapis"]

[[plugins]]
package = "@netlify/plugin-functions-install-core"
