[build]
publish = "public"
command = "echo 'No build step required.'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/secrets/service_account.json"]


[functions."*"]
    external_node_modules = ["googleapis"]

[[plugins]]
package = "@netlify/plugin-functions-install-core"
