[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."submit-request"]
  included_files = ["netlify/functions/secrets/service-account.json"]

[functions."log-tip"]
  included_files = ["netlify/functions/secrets/service-account.json"]
